name: EasyEnchanting
author: PixelAgent007
version: 1.1.0
main: global.oskar.easyenchanting.Main
api-version: 1.19

commands:
  enchantinghelp:
    description: Zeige das Hilfemenu zum Enchanter
    usage: /enchantinghelp